- name: VirtualBox Additions Playbook
  hosts: 127.0.0.1
  sudo: yes
  connection: local

  vars:
    RemoveISO: false
    
  tasks:
    - name: Install pre-reqs for VirtualBox tools
      yum: name={{ item }} state=present
      with_items:
        - gcc 
        - gcc-c++ 
        - kernel-devel
        - kernel-headers
        - make
        - autoconf
        - perl
        - dkms
        - bzip2
      when: ansible_product_name == "VirtualBox" 
      
    - name: Find kernel version
      shell: uname -r
      register: kernel_version
      when: ansible_product_name == "VirtualBox" 
      
    - name: Install kernel-devel
      yum: name=kernel-devel-{{ item }}  state=present
      with_items: kernel_version.stdout  
      when: ansible_product_name == "VirtualBox" 
      
    - name: Find VirtualBox additions iso
      shell: ls /home/vagrant/ | grep VBoxGuest
      register: vbox_additions_iso
      when: ansible_product_name == "VirtualBox" 
    
    - name: Mount VirtualBox tools
      mount: name=/mnt/vboxtools src=/home/vagrant/{{ item }} fstype=iso9660 opts=loop state=mounted
      with_items: vbox_additions_iso.stdout
      when: ansible_product_name == "VirtualBox" 
      ignore_errors: yes   

    - name: VirtualBox additions prereqs
      shell: "{{ item }}"
      with_items:
        - ln -s /usr/include/drm/drm.h /usr/src/kernels/`uname -r`/include/drm/drm.h
        - ln -s /usr/include/drm/drm_sarea.h /usr/src/kernels/`uname -r`/include/drm/drm_sarea.h
        - ln -s /usr/include/drm/drm_mode.h /usr/src/kernels/`uname -r`/include/drm/drm_mode.h
        - ln -s /usr/include/drm/drm_fourcc.h /usr/src/kernels/`uname -r`/include/drm/drm_fourcc.h
      when: ansible_product_name == "VirtualBox" 
      ignore_errors: yes
      
    - name: VirtualBox additions install
      shell: /mnt/vboxtools/VBoxLinuxAdditions.run
      environment:
        KERN_DIR: /usr/src/kernels/`uname -r`
        MAKE: /usr/bin/gmake -i
      when: ansible_product_name == "VirtualBox" 
      ignore_errors: yes
      
    - name: Umount VirtualBox tools
      mount: name=/mnt/vboxtools src=/home/vagrant/{{ item }} fstype=iso9660 opts=loop state=unmounted
      with_items: vbox_additions_iso.stdout
      when: ansible_product_name == "VirtualBox" 
      ignore_errors: yes        
      
    - name: Post VirtualBox tools installation housekeeping
      file: path=/home/vagrant/{{ item }} state=absent
      with_items: vbox_additions_iso.stdout
      when: ansible_product_name == "VirtualBox" and RemoveISO
      ignore_errors: yes